//auth
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CREATE_PROFILE = 'CREATE_PROFILE';

//stories
export const GET_STORIES = 'GET_STORIES';
export const GET_STORY = 'GET_STORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_STORIES_SUBCATEGORIES = 'GET_STORIES_SUBCATEGORIES';
export const POST_STORY = 'POST_STORY';
export const POST_EVENT = 'POST_EVENT';
export const POST_FAVORITE = 'POST_FAVORITE';
export const POST_UNFAVORITE = 'POST_UNFAVORITE';
export const POST_COMMENT = 'POST_COMMENT';
export const GET_STORIES_PROFILE = 'GET_STORIES_PROFILE';
export const UPLOAD_EVENT_IMAGE = 'UPLOAD_EVENT_IMAGE';
export const UPLOAD_STORY_IMAGE = 'UPLOAD_STORY_IMAGE';
export const DELETE_EVENT ='DELETE_EVENT';
export const DELETE_STORY ='DELETE_STORY';

//profile
export const GET_PROFILES= 'GET_PROFILES';
export const GET_PROFILE_HANDLE ='GET_PROFILE_HANDLE';
export const GET_PROFILE = 'GET_PROFILE';
export const POST_PROFILE = 'POST_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';


